# image to inherit from
From python
# usefull variable to see python messages in console
ENV PYTHONUNBUFFERED 1
# copy working file to image
COPY . /code/
# set the workdir as /code/
WORKDIR /code/
# expose port
EXPOSE 8080
# startup commands
CMD ["python", "./index.py"]